# Generated by Django 5.0.6 on 2024-06-24 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='published_date',
            new_name='published_dat',
        ),
    ]
