# Generated by Django 5.0.6 on 2024-06-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_published_dat_blog_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(default='default_name', max_length=40),
            preserve_default=False,
        ),
    ]
